import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";

// components
import { MainTitle } from "@/components/MainTitle";

const inter = Inter({ subsets: ["latin"] });
const lora = Lora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col items-center bg-background">
        <header
          className={`${lora.className} text-primary-foreground flex flex-col items-center  w-full p-4 bg-green-500`}
        >
          <MainTitle />
          {/* HEADER COMPONENTS */}
        </header>
        <main className="">{children}</main>
        <footer className="">{/* FOOTER COMPONENTS */}</footer>
      </body>
    </html>
  );
}
